# Generated by Django 3.1.4 on 2021-01-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('adress', models.CharField(max_length=100)),
                ('cellphone', models.CharField(blank=True, max_length=9, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('adress', models.CharField(max_length=100)),
                ('cellphone', models.CharField(blank=True, max_length=9, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('roomArea', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('roomAdress', models.CharField(blank=True, max_length=100, null=True)),
                ('ownBathroom', models.BooleanField(blank=True, default=True, null=True)),
                ('priceLight', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('priceWater', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('priceInternet', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('priceSignalTelevision', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('priceRoom', models.PositiveSmallIntegerField()),
                ('priceSubTotal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priceTotal', models.PositiveSmallIntegerField()),
                ('dateInitial', models.DateField(blank=True, null=True)),
                ('dateFinal', models.DateField(blank=True, null=True)),
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building')),
                ('floorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
                ('owenerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.owner')),
                ('renterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.renter')),
            ],
        ),
    ]
