# Generated by Django 3.1.4 on 2021-01-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210103_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='priceMaintenance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
