# Generated by Django 3.1.4 on 2021-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210103_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': 'Propietario'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': 'Inquilino'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='Number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='renter',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='renter',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='owner',
            name='adress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='adress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='renter',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
