# Generated by Django 3.1.4 on 2021-01-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210104_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name_plural': '03-Edificios'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['name'], 'verbose_name_plural': '04-Pisos'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': '01-Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': '02-Inquilinos'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['buildingId', 'floorId', 'renterId', 'priceTotal', 'dateInitial', 'dateFinal'], 'verbose_name_plural': '05-Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='buildingId',
        ),
    ]
